[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# Menambahkan dependencies di Cargo.toml
[dependencies]
actix-web = "4.0"
actix-cors = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }